CREATE TABLE super_admins(
    id BIGINT GENERATED ALWAYS as IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE NOT NULL,
    permissions JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TRIGGER set_updated_at_super_admins
BEFORE UPDATE ON super_admins
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();